#ifndef __DIANRU_OBCODE_H__
#define __DIANRU_OBCODE_H__
#define getDianruDeviceOrientation getIteratorPumpkin
#define setDianruRequestLaseTimeWithUrl setPermitTrumpet
#define dianruViewload CreatePiano
#define dianruStartEGOUpdate DeleteLaugh
#define dianruSpendScoreResultCallback EndWithWeed
#define getDianruMainBounds getCollectNoise
#define dianruObjectForKey KillRice
#define dianruDidJumpedView KillLabel
#define YQL_V BlowAchieve
#define dianruFindview MatchCell
#define getDianruAppId getBuildExperience
#define YQLHttpActionExecer ShowTableCell
#define YQLTextField FindCountry
#define dianruWithMySelf FunctionNavigationBar
#define YQLAlignCenter CutInterest
#define dianruNewCheckSum InviteSnake
#define YQLANIMATION_TYPE StartWithView
#define dianruQueryString HashTomato
#define dianruResizeToFit DevelopAchieve
#define dianruAddRefreshView CreateBread
#define YQLMacros AnswerKilometer
#define dianruReadLocationFor CloneForest
#define dianruEnable PrintWindow
#define dianruRequestBlock ServeButton
#define dianruImageFor AddBroccoli
#define YQLTextureInfo CollectFeature
#define dianruTimeout CreateKilometer
#define dianruExpire ChangeAdvice
#define YQLViewUnknow IndexWindow
#define dianruParseEvent FallPotato
#define dianruParseFloat DancePicker
#define dianruDidReportedView CompileAchieve
#define YQLTextureVertical InviteChicken
#define YQLReqestResultType DanceView
#define YQLViewCell AnswerFlower
#define getDianruSpendScore getStudyParrot
#define YQLTextureHorizontal ChangeEgg
#define dianruShareIstance CoverProgress
#define dianruActions KillBroccoli
#define dianruBuildWithName FowardVoice
#define YQLRunningProcess BiteSubject
#define YQLSetAction PutLiberty
#define YQLCodeAction ProductNoodles
#define setDianruNode setIteratorPotato
#define dianruDuration BlowVoice
#define YQLNotificationAction CoverNavigationBar
#define dianruExec FallFeature
#define dianruLoadView ChangeCache
#define dianruApplicationKey HoldLiberty
#define addDianruStyle CompileFeature
#define dianruRequestSpace QueryAchieve
#define dianruCreate CompareAchieve
#define dianruContext LoadTableCell
#define dianruCancel DeleteSegment
#define YQLAlignLeft FunctionBroccoli
#define YQLViewText BorrowEgg
#define initWithDianruContext initLookTabBar
#define dianruName MatchWeed
#define dianruParseTextAttr EndWithWhale
#define getDianruMacAddress getProductWebView
#define setDianruArrowData setRunBroccoli
#define YQLHttpRequest GetPlant
#define dianruSubview CrashSnake
#define setDianruDelegateNull setCompareImage
#define getDianruWifiIP getNextLabel
#define dianruReadNetDataTaskFor QueryWebView
#define dianruStopLoadAnimation ParseFlower
#define YQLViewTextField HashKilometer
#define dianruFsPath ReadEgg
#define dianruRunningProcesses MaintainImage
#define dianruEnableUseRadius CloneCache
#define dianruDidDataReceivedView ReadFeature
#define YQLBeginAction ParseCarrot
#define YQLActionNode IndexVoice
#define dianruWakeup ReadPumpkin
#define YQLFontBold DecorateActivityView
#define YQLViewSection GetBroccoli
#define YQLUrlCache BuildSwitch
#define dianruMovieFinishedCallback DevelopSlider
#define YQLViewSimple RunFlower
#define dianruLoadData FindSegment
#define dianruHide BiteTomato
#define dianruRemove BiteLiberty
#define dianruResult loadActivityView
#define YQLFontStyle_ALL BuildSegment
#define YQLViewDelegate MaintainTrumpet
#define refreshDianruTableHeaderDidTriggerRefresh ParseImage
#define dianruJump DevelopOnion
#define dianruRect LockRadish
#define dianruStartRotation GetOnion
#define YQLViewTable BlowFeature
#define addDianruChild ApendAlertView
#define dianruPurge BlowForest
#define getDianruFreeSpace getFallForest
#define YQLHttpAction AnswerImage
#define YQLOPullRefreshLoading WaitWeed
#define dianruText CollectWebView
#define dianruImage DecorateRice
#define _dianruBuild WaitWhale
#define setDianruImageWithContent setGeneralWindow
#define dianruInitialize DanceOnion
#define YQLRefreshTableHeaderDelegate DoDamage
#define dianruExecuteAnimation LoadCache
#define getDianruLocation getBuildButton
#define dianruMD5Hash ProductWindow
#define setDianruResult setLoadActivityView
#define YQLSectionView LookVoice
#define dianruStopEGOUpdate LoadBread
#define YQLFontDELETE LockFlower
#define refreshDianruScrollViewDidEndDragging DevelopLiberty
#define dianruTimes LoadKilometer
#define dianruParent PermitRadish
#define dianruHandleSingleFingerEvent ChangeSlider
#define YQLNode SetSlider
#define YQLScriptRunner WaitNoise
#define YQLAnimationView DoToolBar
#define YQLViewAnimation BuildWeed
#define dianruTarget ReplaceBelieve
#define getDianruQueryString getPrintView
#define getDianruReportUrl getAddKilometer
#define dianruParseActionNode HoldRice
#define dianruUpdateContent PutBelieve
#define dianruCutStr IteratorWeed
#define dianruCheckSum ServeTableViewCell
#define getDianruWifiInfo getFowardCache
#define setDianruRefreshArrowImage setGeneralLaugh
#define getDianruScore getCrashTree
#define YQLMediaView MaintainFlower
#define refreshDianruTableHeaderDataSourceIsLoading ParseTrumpet
#define YQLTexture CutBread
#define YQLViewInterstitial BorrowSubject
#define dianruUrl DevelopTableCell
#define dianruLocalIPAddress CompareCarrot
#define refreshDianruScrollViewDataSourceDidFinishedLoading NeedPumpkin
#define dianruAnis MatchNoodles
#define dianruWebViewCallBack HoldSpider
#define dianruDataFor FallExperience
#define YQLDelegate CreateBroccoli
#define dianruFsDirectory QueryNavigationBar
#define dianruEncryptWithText PrintLaugh
#define YQLTableSectionView CreateLiberty
#define setDianruState setFallMemory
#define dianruDecodeToUrl CollectBelieve
#define dianruLocation cutVoice
#define YQLTextureType PrintRice
#define dianruDidMainCloseView ApendSlider
#define getDianruFingerprint getKillSubject
#define dianruEvent FowardForest
#define YQLViewHtml MatchCake
#define YQLOPullRefreshPulling FallOnion
#define dianruExit CallInterest
#define dianruParseBackground ProductCarrot
#define YQLViewRoot BlowSlider
#define YQLAction LoadDessert
#define YQLFactory FunctionLiberty
#define YQLDeleteAction IndexToolBar
#define YQLOrientation CoverSlider
#define dianruDiskInfo DancePiano
#define dianruDidViewCloseView ServeBelieve
#define dianruDeviceOrientationDidChange FowardTableCell
#define YQLTextureSimple CostChicken
#define getDianruImage getLockCake
#define dianruRun ParseActivityView
#define dianruWrite KillExperience
#define YQLInterstitialView HoldActivityView
#define dianruURLEncodedString ShowCountry
#define dianruAppuserid DecorateDessert
#define dianruExecOne BiteTable
#define YQLViewAction LoadPlant
#define getDianruMachineName getGetView
#define dianruShowLoadAnimation StudySegment
#define dianruKeyForString FunctionButton
#define dianruWithData ProductRadish
#define dianruMoviePlayerLoadStateChanged DanceToolBar
#define dianruFrame makeFeature
#define YQLSimpleView ChangeSegment
#define YQLUIModel GeneralKilometer
#define dianruDeviceString BeatNoise
#define dianruCreateWithView LockEgg
#define dianruShow SetDamage
#define dianruOn DevelopPiano
#define dianruReportData GetExperience
#define YQLIfAction MakeDessert
#define dianruParseHex EndWithPicker
#define dianruCacheTimeList IteratorAlertView
#define YQLScript ReplaceActivityView
#define dianruHTTPResultCallback StudyOnion
#define dianruScoreResultCallback PutInterest
#define dianruKeychainIdfa KillVoice
#define getDianruTimestamp getLoadSlider
#define dianruSuspend FindEgg
#define dianruDelegate HashSubject
#define dianruWithRequst PutSwitch
#define dianruWithUrl LoadNavigationBar
#define dianruHash DoSwitch
#define getDianruOSVersion getIteratorKilometer
#define dianruStartAni ProductForest
#define YQLView KillForest
#define YQLFontStyleNode BlowOnion
#define dianruStopRotation CompareWeed
#define dianruDisposeContent BlowButton
#define dianruWithCallback BiteToolBar
#define dianruFindView CompareTree
#define dianruURLDecodedString ShowSnake
#define YQLViewNode DeleteMemory
#define YQLTextureLoop ApendMemory
#define getDianruUserId getChangeChicken
#define dianruNode iteratorPotato
#define dianruStopAnimation MakePotato
#define dianruUrlToDecode HashAdvice
#define dianruParseInsets KillLiberty
#define dianruKeychainMac CrashNoodles
#define YQLAlign ApendInterest
#define dianruRegistClickEvent AddLabel
#define YQLViewLoader DecorateCell
#define refreshDianruScrollViewDidScroll GeneralPumpkin
#define YQLTextView BuildSlider
#define YQLEncryptUtil ChangePumpkin
#define YQLViewUtil CoverOnion
#define YQLRefreshTableView_LastRefresh QueryEgg
#define dianruString2Hex CollectBear
#define YQLLabelUpdate EndWithTableViewCell
#define dianruView CutPicker
#define YQLCheckSum BuildTable
#define YQLFontNormal CompileForest
#define dianruDecryptWithText ApendRice
#define dianruDidViewOpenView ParseTomato
#define YQLContext DeletePumpkin
#define dianruSysctlbynameFctn ChangeWeed
#define YQLGTMBase64 NeedSlider
#define dianruParseStyleAttr DevelopPumpkin
#define YQLOPullRefreshNormal CreateSegment
#define YQLKey BlowMemory
#define YQLTALKINGTYPE MakeInterest
#define YQLFontUnderLine PutAlertView
#define YQLSdkInfo BlowPotato
#define dianruContent addBear
#define setDianruContent setAddBear
#define dianruData FowardDessert
#define dianruForKey BlowWhale
#define onDianruAdClickADID SetWindow
#define getDianruScreenFrame getHoldPiano
#define dianruDoneLoadingTableViewData ParseSubject
#define dianruLayer BuildRice
#define dianruClose DevelopBear
#define YQLTalkingDataAction BeatCell
#define dianruCode FunctionCarrot
#define refreshDianruLastUpdatedDate BlowAlertView
#define getDianruHttpFail getDeleteDolphin
#define YQL_TK_CLICK CloneDolphin
#define dianruImageResultCallback NeedSegment
#define YQLViewType CloneInterest
#define YQLTableCell BorrowTableCell
#define YQLCacheRequest BorrowLabel
#define dianruDecode SleepForest
#define getDianruDiskid getSleepCarrot
#define YQL_TK_DISPLAY MakeNavigationBar
#define YQLStyleNode QueryRadish
#define YQLEngine CloneButton
#define dianruScreenRotation BeatTable
#define getDianruKey getGetToolBar
#define dianruEnableRequestWithUrl GeneralOnion
#define YQLTextureFull BiteImage
#define YQLOpenAction CoverNoodles
#define YQLViewFactory ChangeTrumpet
#define YQLBorder AnswerAchieve
#define YQLFileSystem CreateTrumpet
#define dianruIsModify BorrowLiberty
#define dianruCenter ChangeToolBar
#define YQLViewImage IndexFlower
#define dianruReloadTableViewDataSource EndWithCell
#define YQLDeviceInfo SleepChicken
#define dianruParseStyle LockAchieve
#define YQLFontStyle CompareLaugh
#define setDianruLocation getCutVoice
#define dianruParseBorder ProductProgress
#define dianruParseView DevelopTree
#define dianruFormat MakeSubject
#define dianruObject QueryTable
#define dianruDidClickedView CollectSlider
#define YQLAlignRight BiteSnake
#define dianruKey IteratorCountry
#define dianruMasks LockCarrot
#define YQLRefreshTableHeaderView ReadAdvice
#define dianruPadding ServeAlertView
#define dianruMethod NextPlant
#define refreshDianruTableHeaderDataSourceLastUpdated FallTable
#define dianruSpaceUrl ParseBear
#define dianruWith ReplaceKilometer
#define dianruDrawType CompileTomato
#define dianruLocalWiFiAvailable HashWeed
#define dianruSubviews PrintToolBar
#define YQLPullRefreshState DecorateTomato
#define dianruLoadani SetNoise
#define getDianruWithIDFA getBeatToolBar
#define dianruParseRect QueryFeature
#define dianruParseColor LockLiberty
#define dianruTimerAction FowardTabBar
#define YQLEndAction FowardAlertView
#define onDianruAdDisplayADID SetView
#define dianruTo CallChicken
#define dianruLoad SetCarrot
#define getDianruWifiSSID getParseVoice
#define YQLTextFieldBri CrashCarrot
#define YQLTalkingData PutPicker
#define dianruParseAlign CostView
#define YQLHtmlView BuildWhale
#define dianruDecodeOne WaitButton
#define dianruBuild CallTree
#define addDianruEvent NextTomato
#define dianruChecksum3 PrintTrumpet
#define dianruAddCallback BlowCache
#define dianruChecksum2 PutSnake
#define dianruChecksum1 LoadWindow
#define dianruBind DanceImage
#define dianruDrawTexture StudyLiberty
#define setDianruImageWithUrl setBeatNavigationBar
#define isDianruJailbroken FindWebView
#define getDianruBaseUrl getStartWithExperience
#define dianruValue ClonePiano
#define dianruCarrierName ServeBear
#define dianruSubType CompileImage
#define YQLTableView BeatLiberty
#define dianruParseFontStyle CutBelieve
#define YQLViewMedia BrushSnake
#define dianruClearup EndWithSegment
#define dianruAddCell DanceDamage
#define dianruState fallMemory
#define YQLAlertAction InviteTabBar
#define dianruCloseMain GetPicker
#define dianruType IndexTableViewCell
#define dianruParseConf CoverToolBar
#define YQLUtil StartWithInterest
#define YQLEventManager FindTomato
#define setDianruViewNode setPrintKilometer
#define setDianruFrame setMakeFeature
#define YQLAnimationAction LoadDolphin
#define YQL_TK_UNKNOW LockLabel
#define dianruCallback MakeExperience
#define YQLDataCache CutWebView
#define YQLLoader BeatSubject
#define dianruStartAniType BorrowTabBar
#define YQLOpenUDID LockVoice
#define YQLLocation PutCake
#define YQL_H SleepSlider
#define dianruUpdate CompareAlertView
#define dianruParseViewType StartWithWeed
#define dianruStartAnimation BiteTableCell
#define YQLImageView StartWithLabel
#define YQLSDK GeneralCountry
#define YQLWebView CollectLaugh
#define dianruParseTextureType GetFlower
#define dianruRequest BeatTabBar
#define dianruExecIfElse ApendButton
#define dianruCheckIsNeedModify StartWithParrot
#define getDianruDiskTotalSpaceEx getCallAdvice
#define dianruFileIsExists CloneNoodles
#endif /*__DIANRU_OBCODE_H__*/
